version: 2.1

jobs:
  dev:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make init
      - run:
          name: Linting
          command: make lint
      - run:
          name: Testing
          command: make test
  prod:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: build
          command: echo "Build in progress.."
      - run:
          name: deploy
          command: echo "Deployment in progress.."

workflows:
  dev-worklow:
    jobs:
      - dev:
          filters:
            branches:
              only:
                - dev
  prod-workflow:
    jobs:
      - prod:
          filters:
            branches:
              only:
                - master