name: Pyalb Prod Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - run: python -m pip install -r requirements.txt
      - run: echo "Installation complete"
      - run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: pyalb-build-artifacts
          path: dist/